server:
  port: 7979
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mail
    username: root
    password: 365373011
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      max-lifetime: 20
      auto-commit: true
      idle-timeout: 60000
      pool-name: DateSourceHikariCP
      maximum-pool-size: 1800000
      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1
    port: 6379
    password: 990728
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl